// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injection

import (
	"github.com/take0fit/ddd-clean-temp/internal/common/db"
	"github.com/take0fit/ddd-clean-temp/internal/user/application/service"
	"github.com/take0fit/ddd-clean-temp/internal/user/infrastructure"
	"github.com/take0fit/ddd-clean-temp/internal/user/interface/controller"
)

// Injectors from wire.go:

func InitializeUserController() *controller.UserController {
	dbDB := db.GetDB()
	userRepository := infrastructure.NewUserRepository(dbDB)
	userService := service.NewUserService(userRepository, dbDB)
	userController := controller.NewUserController(userService)
	return userController
}
