// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injection

import (
	"github.com/take0fit/ddd-clean-temp/internal/auth/application/usecase"
	"github.com/take0fit/ddd-clean-temp/internal/auth/infrastructure/db"
	"github.com/take0fit/ddd-clean-temp/internal/auth/infrastructure/repository"
	"github.com/take0fit/ddd-clean-temp/internal/auth/interface/controller"
)

// Injectors from wire.go:

func InitializeAuthController() *controller.AuthController {
	dbDB := db.GetDB()
	authRepository := repository.NewAuthRepository(dbDB)
	authUsecase := usecase.NewAuthUsecase(authRepository, dbDB)
	authController := controller.NewAuthController(authUsecase)
	return authController
}
