version: "3.8"
services:
  app:
    build:
      dockerfile: ./docker/local/Dockerfile
      context: .
      target: debugger
    env_file: .env
    ports:
      - 8080:8080
      - 2345:2345
    volumes:
      - .:/go/src/github.com/take0fit/ddd-clean-temp
    depends_on:
      - auth_db
      - user_db

  auth_db:
    image: postgres:13
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  user_db:
    image: postgres:13
    environment:
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: user_password
      POSTGRES_DB: user_db
    volumes:
      - user_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # 内部と外部のポートを一致させる

volumes:
  auth_db_data:
  user_db_data:
